spring:
  datasource:
    url: jdbc:mysql://10.10.10.102:3306/jboot_pgy?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true 
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: casper
    password: 12345678
   
   
  jpa:
    hibernate:
      ddl-auto: update
  
    generate-ddl: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect